Description: >
    Udacity proj - High Availability Web App

Resources:
      VPC: 
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true
      Ec2Instance:
        Type: 'AWS::EC2::Instance'
        Properties:
            KeyName: udacity
            ImageId: 'ami-04e9aec1ab665f323' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
