version: 2.1

jobs:
  smoke_test:
      docker:
        - image: alpine:latest
      steps:
        - run: apk add --update curl
        - run:
            name: smoke test.
            command: |
              URL="https://blog.udacity.com/"
              if curl -s --head ${URL} # test if blog.udacity. com exists
              then
               echo "It worked!"
              else
               echo "It not worked!"
              fi

workflows:
  my_workflow:
    jobs:
      - smoke_tests